### ISSUE TITLE
Fix get alpha opacity in IE8

### ISSUE THREAD

**Issue by mescoda** [jquery/jquery#1705]
When setting opacity to an element in IE8+, according to http://www.quirksmode.org/css/opacity.html I can use

``` css
.opacity {
    filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=50);
    opacity: 0.5;
}
```

note that the `opacity` in IE8 filter is in upper case

but jQuery 1.\* currently only support getting the result setted in lower case `opacity`, like `filter: progid:DXImageTransform.Microsoft.Alpha(opacity=50);`

see demo http://jsfiddle.net/c9d5ctfa/ in IE8

Also in [MSDN](http://msdn.microsoft.com/en-us/library/ms532967.aspx), both upper case and lower case are used in the examples.

My PR: https://github.com/jquery/jquery/pull/1704
