### ISSUE TITLE
`offset` method returns incorrect value in Firefox

### ISSUE THREAD

**Issue by anseki** [jquery/jquery#3080]
Hi,
I found a case that `offset` method returns incorrect value in Firefox.
`offset` method subtracts `docElem.clientTop/clientLeft` (i.e. `border-width` of `html` element), but Firefox seems to return `0` as `clientTop/clientLeft` of `html` element always.

For example:
https://jsfiddle.net/xwuc0g6q/

``` html
<html>
  <body>
    <div id="box1"></div>
  </body>
</html>
```

``` css
html {
  border: 10px solid red;
}

body {
  border: 10px solid blue;

  margin: 20px;
  padding: 30px;

  /*position: relative;*/
}

#box1 {
  position: absolute;
  left: 0;
  top: 0;
  width: 50px;
  height: 50px;
  background-color: green;
}
```

``` js
$(function() {

  var elem = document.getElementById('box1');

  // <html>.clientLeft/clientTop
  // from https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/offset.js#L78
  var doc = elem.ownerDocument,
    docElem = doc.documentElement;
  console.log(docElem.tagName + ' > clientLeft: ' + docElem.clientLeft + ' clientTop: ' + docElem.clientTop);

  // document.body.clientLeft/clientTop
  var body = document.body;
  console.log(body.tagName + ' > clientLeft: ' + body.clientLeft + ' clientTop: ' + body.clientTop);

  // getBoundingClientRect
  var box = elem.getBoundingClientRect();
  console.log('BoundingBox > left: ' + box.left + ' top: ' + box.top);

  // jQuery#offset
  var offset = $(elem).offset();
  console.log('offset() > left: ' + offset.left + ' top: ' + offset.top);

});
```

Res in Google Chrome:

```
HTML > clientLeft: 10 clientTop: 10
BODY > clientLeft: 10 clientTop: 10
BoundingBox > left: 0 top: 0
offset() > left: -10 top: -10
```

Res in IE:

```
HTML > clientLeft: 10 clientTop: 10
BODY > clientLeft: 10 clientTop: 10
BoundingBox > left: 0 top: 0
offset() > left: -10 top: -10
```

Res in Firefox:

```
HTML > clientLeft: 0 clientTop: 0
BODY > clientLeft: 10 clientTop: 10
BoundingBox > left: 0 top: 0
offset() > left: 0 top: 0
```

But I can't understand why the method subtracts `docElem.clientTop/clientLeft`.
If it do that for getting the position relative to the document, it should calculate based on `border-box` (i.e. outline that includes border). The `box1` element in above code is positioned based on `border-box` even if `html` has border.
And also, `html` usually has no border.

Then, I feel that `left: 0, top: 0` is correct result, and it is useful.

**Comment by dmethvin** [comment]
> If it do that for getting the position relative to the document, it should calculate based on border-box (i.e. outline that includes border)
The jQuery code predates the existence of `border-box` by several years, so it may have just been overlooked.

> And also, html usually has no border.
I suspect that is why this hasn't been reported or noticed, if it is actually a bug.

> Then, I feel that left: 0, top: 0 is correct result, and it is useful.

If the HTML element has a border would the position be from the inside of the border, or the outside? I don't know and a quick search into the specs didn't help.

Now we need some people who actually understand how we got here. Maybe @mikesherov ?

**Comment by hexalys** [comment]
Very odd. If anything it should add margins in `border-box` box-sizing context.

I have just filed a Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1268280) for the clientLeft/clientTop issue.

**Comment by gibson042** [comment]
`<html>` border/padding and `<body>` margin/border/padding have always made things tricky, but defining `.offset()` to be "relative to the document" means that correct behavior is that for which the `top` and `left` values match fixed positioning (i.e., the original `left: 0, top: 0` proposal of this issue).

**Comment by anseki** [comment]
I see.
One of important points is:
As I said, positioning by CSS uses border-box. Therefore jQuery methods that use CSS positioning are incompatible with `offset` method.
`offset(coordinates)` method (i.e. setter) is also incompatible.
For example:
https://jsfiddle.net/0ac41fxw/

```html
<html>
  <body>
    <div id="box1"></div>
    <div id="box2"></div>
  </body>
</html>
```

```css
html {
  border: 10px solid red;
}

body {
  border: 10px solid blue;
  margin: 20px;
  padding: 30px;
}

#box1, #box2 {
  position: absolute;
  width: 50px;
  height: 50px;
}

#box1 {
  background-color: rgba(0, 128, 0, 0.5); /* translucent green */
  left: 0;
  top: 0;
}

#box2 {
  background-color: rgba(128, 0, 0, 0.5); /* translucent red */
}
```

```js
$('#box2').offset($('#box1').offset());
```

I gave a `coordinates` that was given from `offset` method to `offset` method. Then I expected `box2` to be positioned at the position of `box1`.

Chrome:
![ch](https://cloud.githubusercontent.com/assets/4763469/14877346/39567e50-0d57-11e6-9d27-d8e6047334aa.png)

IE:
![ie](https://cloud.githubusercontent.com/assets/4763469/14877353/4a68a6c8-0d57-11e6-8d32-4b50a5891d8f.png)

Firefox:
![ff](https://cloud.githubusercontent.com/assets/4763469/14877356/54f332ac-0d57-11e6-915f-c83064f857ce.png)

Result in Firefox seems correct.

The setter of `offset` method (`jQuery.offset.setOffset`) seems to subtract `left/top` that was returned by `offset` from passed `left/top`. The passed `left/top` were already subtracted. That is, those were subtracted twice. Therefore the element was positioned at `20px` shifted point (not `10px`).
